train:
  total_steps: 1000
  lr: 2.0e-4
  warmup_steps: 10
  weight_decay: 0.01
  batch_size_per_device: 4
  grad_accum_steps: 2 
  mixed_precision: fp16
  clip_grad: 1.0

switchable:
  configs: ["configs/bitwidth_uniform.yaml", "configs/bitwidth_mixed_small.yaml"]
  schedule: "round_robin"

cyclic:
  cycle_every_steps: 50
  order: ["uniform8", "mixed8648"]
